apiVersion: v1
kind: Secret
metadata:
  name: domain-runtime-encrypt-secret
  namespace: default
type: Opaque
data:
  username: d2VibG9naWM=
  password: d2VibG9naWMxMg==
  
---
apiVersion: v1
kind: Secret
metadata:
  name: test-domain-weblogic-credentials
  namespace: default
type: Opaque
data:
  username: d2VibG9naWM=
  password: d2VibG9naWMxMg==
  